FROM ubuntu:22.04
RUN apt-get update
RUN apt-get install -y wget gnupg
RUN dpkg --add-architecture i386
RUN mkdir -pm755 /etc/apt/keyrings
RUN wget -O - https://dl.winehq.org/wine-builds/winehq.key | gpg --dearmor -o /etc/apt/keyrings/winehq-archive.key -
RUN wget -NP /etc/apt/sources.list.d/ https://dl.winehq.org/wine-builds/ubuntu/dists/jammy/winehq-jammy.sources
RUN apt-get update
RUN apt-get install -y libpipewire-0.3-dev libglib2.0-dev gcc g++ make
RUN apt-get install -y --install-recommends wine-devel-dev winehq-devel
